/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.myapplication.database;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType DietRecord.
 *
 * @since 2022-09-22
 */
@PrimaryKeys({"uid", "date", "time"})
@Indexes({"RD:uid,date,time"})
public final class DietRecord extends CloudDBZoneObject {
    private String uid;

    private String date;

    private String time;

    @DefaultValue(stringValue = "\"unknown\"")
    private String foodname;

    @DefaultValue(floatValue = 0.0F)
    private Float heat;

    @DefaultValue(floatValue = 0.0F)
    private Float fat;

    @DefaultValue(floatValue = 0.0F)
    private Float protein;

    @DefaultValue(floatValue = 0.0F)
    private Float carbohydrate;

    @DefaultValue(floatValue = 0.0F)
    private Float ca;

    @DefaultValue(floatValue = 0.0F)
    private Float fe;

    public DietRecord() {
        super(DietRecord.class);
        this.foodname = "\"unknown\"";
        this.heat = 0.0F;
        this.fat = 0.0F;
        this.protein = 0.0F;
        this.carbohydrate = 0.0F;
        this.ca = 0.0F;
        this.fe = 0.0F;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getTime() {
        return time;
    }

    public void setFoodname(String foodname) {
        this.foodname = foodname;
    }

    public String getFoodname() {
        return foodname;
    }

    public void setHeat(Float heat) {
        this.heat = heat;
    }

    public Float getHeat() {
        return heat;
    }

    public void setFat(Float fat) {
        this.fat = fat;
    }

    public Float getFat() {
        return fat;
    }

    public void setProtein(Float protein) {
        this.protein = protein;
    }

    public Float getProtein() {
        return protein;
    }

    public void setCarbohydrate(Float carbohydrate) {
        this.carbohydrate = carbohydrate;
    }

    public Float getCarbohydrate() {
        return carbohydrate;
    }

    public void setCa(Float ca) {
        this.ca = ca;
    }

    public Float getCa() {
        return ca;
    }

    public void setFe(Float fe) {
        this.fe = fe;
    }

    public Float getFe() {
        return fe;
    }

}
